name: Tests

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"
jobs:
  test:
    name: test script in docker
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - name: Build Docker image
        run: docker build -t ubuntu-config .

      - name: Run script in container
        run: docker run --rm ubuntu-config
